server:
  port: 8672

spring:
  application:
    name: sport-team-management
  datasource:
    url: jdbc:postgresql://localhost:2998/sport?currentSchema=management
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        timezone:
          default_storage: NORMALIZE
        format_sql: true
        dialect: org.hibernate.dialect.PostgresPlusDialect
  flyway:
    enabled: true
  jmx:
    enabled: true

springdoc:
  swagger-ui:
    use-root-path: true
    disable-swagger-default-url: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/